name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Check Node and npm
        run: |
          node --version
          npm --version
      - name: install dependecies
        run: |
          npm ci
          working-directory: backend