name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Check Node and npm
        run: |
          node --version
          npm --version

      - name: Debug files
        run: |
          pwd
          ls -la
          echo "----- backend -----"
          ls -la backend
          echo "----- package-lock -----"
          ls -la backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: backend