name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "KK Store backend CI is running!"